# Generated by Django 4.0.4 on 2022-07-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_date_created_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
