# Generated by Django 4.0.4 on 2022-07-16 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_question_date_created_alter_reply_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 8, 58, 17, 636005, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 8, 58, 17, 637006, tzinfo=utc)),
        ),
    ]
