# Generated by Django 4.0.4 on 2022-07-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='votePoints',
        ),
    ]
