# Generated by Django 4.0.4 on 2022-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votePoints',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reply',
            name='votePoints',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
