# Generated by Django 4.0.4 on 2022-07-07 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('english', 'English'), ('mandarin', 'Mandarin'), ('german', 'German')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
