# Generated by Django 4.0.4 on 2022-07-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_question_topic_question_topic_delete_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votePoints',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
