# Generated by Django 4.0.4 on 2022-07-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_reply_votepoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('English', 'English'), ('English', 'Mandarin'), ('English', 'German')], max_length=200),
        ),
    ]
